 printf("void compact_2(){ \n");
    printf("    int* posi; \n");
    printf("    int node[TAB_LENGTH];\n");
    printf("    FILE *read; \n");
    printf("    read = fopen(filename, %cr%c); \n", 34, 34);
    printf("    char delim[] = %c %c; \n", 34,34);
    printf("    char str[50]; \n");
    printf("    int size = 0; \n");
    printf("    int last = 0; \n");
    printf("    int find = 0; \n");
    printf("    int n1, n2, h = 4; \n");
    printf("    const char* s; \n\n\n");
    printf("    if(NULL == read) { \n");
    printf("        printf(%c file can't be opened%cn%c);\n", 34, 92,34);
    printf("    }\n\n");
    printf("while(fgets(str, 50, read) != NULL){ \n");
    printf("    s = strtok(str, delim);\n");
    printf("    sscanf(s, %c%cd%c, &n1); \n", 34,37,34);
    printf("    find = 0; \n");
    printf("    s = strtok(NULL, delim); \n");
    printf("    sscanf(s, %c%cd%c, &n2); \n", 34,37,34);
    printf("    for(int i = 0; i < size; i = i+2) \n");
    printf("        if(posi[i] == n1){ \n");
    printf("            posi[i+1]++; \n");
    printf("            find = 1;  \n");
    printf("            if (n1 == 0) \n");
    printf("                last = last +2; \n");
    printf("            break; \n");
    printf("        }\n\n");
    printf("    if(find != 1){ \n");
    printf("        if(last+2 <= size){ \n");
    printf("            posi[last] = n1; \n");
    printf("            posi[last+1]++; \n");
    printf("            node[last] = n2; \n");
    printf("            last = last + 2; \n");
    printf("            find = 1; \n");
    printf("        }\n");
    printf("        else{ \n");
    printf("            posi = realloc(posi, (40+size)*sizeof(int)); \n");
    printf("            size = size + 39; \n");
    printf("            for(int i = 0; i < 40; i++) \n");
    printf("                posi[size - i] = 0; \n");
    printf("            posi[size] = n1; \n");
    printf("            node[size] = n2; \n");
    printf("            size++; \n");
    printf("            posi[size] = 1; \n");
    printf("        }\n");
    printf("     } \n");
    printf(" } \n");
    printf("    puts(%cdone%c); \n", 34, 34);
    printf("    fclose(read); \n\n");
    printf("    fp = fopen(filename, %cw%c); \n", 34, 34);
    printf("    for(int i = 0; i < size; i = i+2) \n");
    printf("    if(posi[i] != 0) \n");
    printf("        fprintf(fp,%c%cd %cd %cd %cn%c, posi[i], node[i], posi[i+1]); \n", 34, 37, 37,37, 92, 34);
    printf("    fclose(fp); \n");
    printf("}\n \n");

    printf("void compact(){\n\n");
    printf("    int pos[2*TAB_LENGTH] = {0};\n");
    printf("    int node[2*TAB_LENGTH]; \n");
    printf("    FILE *read; \n");
    printf("    read = fopen(filename, %cr%c);\n", 34, 34);
    printf("    char delim[] = %c %c;\n", 34,34);
    printf("    char str[50];\n");
    printf("    int n1, n2, h = 4;\n");
    printf("    const char* s;\n\n");
    printf("    if(NULL == read) {\n");
    printf("            printf(%c file can't be opened%cn%c);\n", 34,92,34);
    printf("    }\n\n");
    printf("    while(fgets(str, 50, read) != NULL){\n");
    printf("        s = strtok(str, delim);\n");
    printf("        sscanf(s, %c%cd%c, &n1);\n", 34,37,34);
    printf("        pos[n1]++;\n");
    printf("        s = strtok(NULL, delim);\n");
    printf("        sscanf(s, %c%cd%c, &n2);\n",34,37,34);
    printf("        node[n1] = n2; \n }\n");
    printf("    puts(%cdone%c);\n", 34, 34);
    printf("    fclose(read);\n \n");
    printf("    fp = fopen(filename, %cw%c);\n\n", 34, 34);
    printf("    for(int i = 0; i < 2*TAB_LENGTH; i++) \n");
    printf("        if(pos[i] != 0)\n");
    printf("            fprintf(fp,%c%cd %cd %cd %cn%c, i, node[i], pos[i]);\n\n", 34,37,37,37,92,34);
    printf("    fclose(fp);\n}\n");
